FROM ghcr.io/ytsaurus/spyt:2.0.0

COPY ./spyt_image/spark-3.2.2-bin-hadoop3.2.tgz /data/
COPY ./publisher/spark_distrib.py /scripts/spark_distrib.py 
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
#ENTRYPOINT ["/bin/bash"]